version: "3.5"

volumes:
  gitlab-logs:
  gitlab-data:
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://192.168.99.100';"
    volumes:
    - ./config:/etc/gitlab
    - gitlab-logs:/var/log/gitlab
    - gitlab-data:/var/opt/gitlab
    ports:
    - 443:443
    - 80:80
    - 22:22
    restart: on-failure